name: Static Code Analysis
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  mobile-dart-analyze:
    name: Run Dart Code Analysis
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: ./mobile
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Setup Mise
        uses: immich-app/devtools/actions/use-mise@3bca63ca3c15020293b36b51737a3ee2c773340b # use-mise-action-v3.1.0
        with:
          github_token: ${{ github.token }}
          working_directory: ./mobile

      - name: Install dependencies
        run: mise //mobile:install:ci

      - name: Install dependencies for UI package
        run: flutter pub get --enforce-lockfile
        working-directory: ./mobile/packages/ui

      - name: Generate translation files
        run: mise //mobile:codegen:translation

      - name: Run Build Runner
        run: mise //mobile:codegen:dart

      - name: Generate platform API
        run: mise //mobile:codegen:pigeon

      - name: Find file changes
        uses: tj-actions/verify-changed-files@a1c6acee9df209257a246f2cc6ae8cb6581c1edf # v20.0.4
        id: verify-changed-files
        with:
          files: |
            mobile/**/*.g.dart
            mobile/**/*.gr.dart
            mobile/**/*.drift.dart
            mobile/**/*.g.swift
            mobile/**/*.g.kt

      - name: Verify files have not changed
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        env:
          CHANGED_FILES: ${{ steps.verify-changed-files.outputs.changed_files }}
        run: |
          echo "ERROR: Generated files not up to date! Run 'mise //mobile:codegen:dart' and 'mise //mobile:codegen:pigeon'"
          echo "Changed files: ${CHANGED_FILES}"
          exit 1

      - name: Run analyze
        run: dart analyze --fatal-infos

      - name: Run format
        run: mise //mobile:format
